//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int id_user { get; set; }
        public string access_token { get; set; }
        public string refresh_token { get; set; }
        public System.DateTime last_refresh { get; set; }
    }
}
