//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<bool> email_confirmed { get; set; }
        public Nullable<System.DateTime> date_registration { get; set; }
        public bool blocked { get; set; }
        public Nullable<System.DateTime> date_blocking { get; set; }
    }
}
