//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPassword
    {
        public int user_id { get; set; }
        public string passwrod_hash { get; set; }
    }
}
